# Generated by Django 4.2.7 on 2023-11-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0004_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="doctor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="first_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(max_length=25),
        ),
    ]
