# Generated by Django 4.2.7 on 2023-11-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0005_timeslot_alter_doctor_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "repeat_days",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of days (e.g., 'mon,tue,thu')",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
