# Generated by Django 4.2.7 on 2023-11-17 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0007_timeslot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
