# Generated by Django 4.2.7 on 2023-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0008_delete_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
