# Generated by Django 4.2.7 on 2023-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0009_alter_timeslot_end_time_alter_timeslot_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
