# Generated by Django 4.2.7 on 2023-11-17 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0011_rename_fees_timeslotpreset_new_patient_fees_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="patient_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif", "pdf"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient_files",
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_files",
            field=models.ManyToManyField(blank=True, to="idas.patientfile"),
        ),
    ]
