# Generated by Django 4.2.7 on 2023-11-17 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0012_patientfile_remove_appointment_patient_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient_files",
        ),
        migrations.DeleteModel(
            name="PatientFile",
        ),
    ]
