# Generated by Django 4.2.7 on 2023-12-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0014_patientfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="updated_at",
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("preset", "start_time"), name="unique_start_time_per_preset"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("preset", "end_time"), name="unique_end_time_per_preset"
            ),
        ),
    ]
