# Generated by Django 4.2.7 on 2023-12-06 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0015_remove_timeslot_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
