# Generated by Django 4.2.7 on 2023-12-06 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0016_timeslot_created_at_timeslot_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeslot",
            name="unique_start_time_per_preset",
        ),
        migrations.RemoveConstraint(
            model_name="timeslot",
            name="unique_end_time_per_preset",
        ),
    ]
