# Generated by Django 4.2.7 on 2023-12-07 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0017_remove_timeslot_unique_start_time_per_preset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("arrived", "Arrived"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancel_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prescriptions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "gif", "pdf"]
                    )
                ],
            ),
        ),
    ]
