# Generated by Django 4.2.7 on 2023-12-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0018_appointment_appointment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientfile",
            name="name",
            field=models.CharField(default="default name", max_length=255),
            preserve_default=False,
        ),
    ]
