# Generated by Django 4.2.7 on 2023-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0019_dayoff_patientfile_name_patientfile_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_subheading",
                    models.CharField(default="Hi there, this is:", max_length=255),
                ),
                (
                    "hero_heading",
                    models.CharField(default="Dr. ABCD XYZ", max_length=255),
                ),
                (
                    "hero_desc",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, ducimus enim fuga fugiat maxime quis rerum sit voluptates."
                    ),
                ),
                (
                    "hero_btn_1_text",
                    models.CharField(default="Get Appointment", max_length=255),
                ),
                (
                    "hero_btn_2_text",
                    models.CharField(default="Contact for business", max_length=255),
                ),
                ("hero_image", models.ImageField(upload_to="site_files/")),
                (
                    "speciality_heading",
                    models.CharField(default="MY SPECILITIES", max_length=255),
                ),
                (
                    "work_history_heading",
                    models.CharField(default="WORK HISTORY", max_length=255),
                ),
                (
                    "qualification_heading",
                    models.CharField(default="QUALIFICATION", max_length=255),
                ),
                (
                    "contact_heading",
                    models.CharField(default="GET IN TOUCH", max_length=255),
                ),
                (
                    "contact_desc",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur consequuntur dicta dolorem eaque earum eos excepturi fugiat hic impedit labore."
                    ),
                ),
                (
                    "contact_btn_1_text",
                    models.CharField(default="GET APPOINTMENT", max_length=255),
                ),
                (
                    "contact_btn_2_text",
                    models.CharField(default="SEND MESSAGE", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
