# Generated by Django 4.2.7 on 2023-12-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0019_patientfile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientfile",
            name="file",
            field=models.ImageField(upload_to="patient_files/"),
        ),
    ]
