# Generated by Django 4.2.7 on 2023-12-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0020_siteinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="site_files/"),
        ),
    ]
