# Generated by Django 4.2.7 on 2023-12-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("idas", "0022_qualification_speciality_workhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preset_manager",
                to="idas.timeslotpreset",
            ),
        ),
    ]
